language: r
cache: packages

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false
  - MAKEFLAGS="-j 2"

r_packages:
  - covr
  - devtools
  - roxygen2

before_install:
  - Rscript -e 'devtools::document()'

after_success:
  - Rscript -e 'covr::codecov()'

