language: r

env:
  - LINTR_COMMENT_BOT=true

r_binary_packages:
  - Rcpp
  - testthat

r_github_packages:
  - jimhester/covr
  - jimhester/lintr
  - allr/rcov

script:
  - make install
  - make check
  - make test

after_success:
  - Rscript -e 'covr::codecov()'
